# Generated by Django 4.2.3 on 2023-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='Data_de_nascimento',
        ),
        migrations.AddField(
            model_name='jogador',
            name='idade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
