# Generated by Django 4.2.3 on 2023-07-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_remove_jogador_data_de_nascimento_jogador_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='assistências',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='gols',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='partidas',
            field=models.IntegerField(default=True),
        ),
    ]
