# Generated by Django 4.2.3 on 2023-07-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0003_jogador_assistências_jogador_gols_jogador_partidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidas', models.IntegerField(default=True)),
                ('gols', models.IntegerField(default=True)),
                ('assistências', models.IntegerField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='assistências',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='gols',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='partidas',
        ),
    ]
