# Generated by Django 4.2.3 on 2023-07-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0004_dados_remove_jogador_assistências_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='assistências',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dados',
            name='gols',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dados',
            name='partidas',
            field=models.IntegerField(default=0),
        ),
    ]
