# Generated by Django 4.2.1 on 2023-07-23 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0005_alter_dados_assistências_alter_dados_gols_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='jogador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dados.jogador'),
            preserve_default=False,
        ),
    ]
