# Generated by Django 4.2.1 on 2023-07-24 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0006_dados_jogador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='jogador',
        ),
    ]
