# Generated by Django 4.2.1 on 2023-07-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0008_dados_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='temporada',
            field=models.IntegerField(default=0),
        ),
    ]
