# Generated by Django 4.2.1 on 2023-07-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0010_clube_jogador_clube'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dados.clube'),
        ),
    ]
