# Generated by Django 4.2.1 on 2023-07-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0013_alter_jogador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(default=1, upload_to='jogador_fotos/'),
            preserve_default=False,
        ),
    ]
