# Generated by Django 4.2.1 on 2023-07-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0017_alter_jogador_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='foto',
        ),
        migrations.AddField(
            model_name='jogador',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='jogador_fotos'),
        ),
    ]
