# Generated by Django 4.2.1 on 2023-07-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0018_remove_jogador_foto_jogador_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='jogador_fotos'),
        ),
    ]
