# Generated by Django 4.2.1 on 2023-07-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0020_alter_jogador_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='foto_perfil',
        ),
    ]
