# Generated by Django 4.2.1 on 2023-07-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0021_remove_jogador_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(default=1, upload_to='jogador_fotos, blank=True, null=True'),
            preserve_default=False,
        ),
    ]
