# Generated by Django 4.2.1 on 2023-07-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0023_alter_jogador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jogador_fotos/'),
        ),
    ]
