# Generated by Django 4.2.1 on 2023-07-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0026_alter_dados_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='foto',
        ),
    ]
