# Generated by Django 4.2.1 on 2023-07-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0027_remove_jogador_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='foto',
        ),
        migrations.AddField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/jogador_fotos/'),
        ),
    ]
