# Generated by Django 4.2.1 on 2023-07-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0031_alter_jogador_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to='jogador_fotos/')),
            ],
        ),
    ]
