# Generated by Django 4.2.1 on 2023-07-28 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0033_remove_jogador_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='jogador',
        ),
        migrations.AddField(
            model_name='jogador',
            name='upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dados.foto'),
            preserve_default=False,
        ),
    ]
