# Generated by Django 4.2.1 on 2023-07-28 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0034_remove_dados_jogador_jogador_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='upload',
        ),
        migrations.AddField(
            model_name='dados',
            name='jogador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dados.jogador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jogador_fotos/'),
        ),
        migrations.DeleteModel(
            name='foto',
        ),
    ]
