# Generated by Django 4.2.1 on 2023-07-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0037_alter_jogador_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='clube',
        ),
        migrations.AlterField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
