# Generated by Django 4.2.1 on 2024-01-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0038_remove_dados_clube_alter_jogador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='clube_detail',
            field=models.IntegerField(default=0),
        ),
    ]
