# Generated by Django 4.2.1 on 2024-01-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0040_alter_dados_clube_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='clube_detail',
            field=models.CharField(max_length=50),
        ),
    ]
